---
downloads: ~/.ansible-downloads/

configure_osx: yes
configure_dockerbar: yes
configure_private_dotfiles: yes

dotfiles_repo: git@github.com:pjanuario/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dev/dotfiles
dotfiles_files:
  - .zshrc
  - .bash_aliases
  - .bashrc
  - .gitconfig
  - .gitignore
  - .osx
private_dotfiles_repo_local_destination: ~/Dropbox/dev/dotfiles
private_dotfiles_files:
  - .machine_aliases
  - .credentials

homebrew_installed_packages:
  # - ansible # Installed initialy
  - dockutil
  - git
  - git-cola
  - httpie
  - mas
  - nvm

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - atom
  - caffeine
  - docker
  - dropbox
  - google-drive
  - google-chrome
  - skype
  - slack
  - spotify
  - spotify-notifications
  - stremio
  - telegram-desktop
  - toggldesktop

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 1001955632  # Disk Cleanup Pro (1.6.0)
  - 443987910   # 1Password (6.5.3)
  - 918858936   # Airmail 3 (3.2.1)
  - 918207447   # Annotate (2.1.4)
  - 406056744   # Evernote ()
mas_email: ""
mas_password: ""

# control items in docker bar
dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Siri

dockitems_to_persist:
  - name: Airmail 3
    path: "/Applications/Airmail 3.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Slack
    path: /Applications/Slack.app
    pos: 3
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 4
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 5
  - name: Calendar
    path: /Applications/Calendar.app
    pos: 6

# atom packages
atom_upgrade_all: False
atom_packages:
  - file-icons
  - highlight-line
  - language-ansible
  - linter
  - pretty-json
