---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: mas_installed_app_ids
    - jgkim.atom

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/dockbar.yml
      when: configure_dockerbar
    - include: tasks/private-dotfiles.yml
      when: configure_private_dotfiles
    - include: tasks/ssh.yml
      when: configure_ssh
    - include: tasks/node.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
      when: configure_osx
