---
  - pause:
      prompt: "Ensure that private_dotfiles are present, in case using dropbox"

  - name: Ensure all configured private dotfiles are links.
    shell: "ls -F {{ dotfiles_home }}/{{ item }}"
    register: existing_dotfile_info
    failed_when: false
    always_run: yes
    changed_when: false
    with_items: "{{ private_dotfiles_files }}"

  - name: Remove existing dotfiles file if a replacement is being linked.
    file:
      path: "{{ dotfiles_home }}/{{ private_dotfiles_files[item.0] }}"
      state: absent
    when: "'@' not in item.1.stdout"
    with_indexed_items: "{{ existing_dotfile_info.results }}"

  - name: Link dotfiles into home folder.
    file:
      src: "{{ private_dotfiles_repo_local_destination }}/{{ item }}"
      dest: "{{ dotfiles_home }}/{{ item }}"
      state: link
    become: no
    with_items: "{{ private_dotfiles_files }}"
